
"Resource/UI/ScoreBoardSurvivor.res"
{
	"SurvivorStatsHead"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"SurvivorStatsHead"
		"xpos"			"4"
		"ypos"			"30"
		"wide"			"21"
		"tall"			"21"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"
		"zpos"			"52"
		"monochrome_color"	"Gray"
	}
	"SurvivorStatsAvatar"
	{
		"ControlName"		"DontAutoCreate"
		"fieldName"		"SurvivorStatsAvatar"
		"xpos"		"26"
		"ypos"		"30"
		"wide"		"12"
		"tall"		"12"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"autoresize"	"3"
		"zpos"			"53"
		"color_outline"	"0 0 0 0"
		"bgcolor_override" ""
	}
	"SurvivorStatsName"
	{
		"ControlName"		"Label"
		"fieldName"		"SurvivorStatsName"
		"xpos"		"39"
		"ypos"		"30"
		"zpos"		"1"
		"wide"		"300"
		"tall"		"18"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"north-west"
		"dulltext"		"0"
		"brighttext"	"1"
		"font"		"DefaultMedium"
		"zpos"			"1111"
		"noshortcutsyntax"		"1"
	}
	"SurvivorStatsNoAvatarName"
	{
		"ControlName"		"Label"
		"fieldName"		"SurvivorStatsNoAvatarName"
		"xpos"		"27"
		"ypos"		"30"
		"zpos"		"1"
		"wide"		"300"
		"tall"		"18"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"north-west"
		"dulltext"		"0"
		"brighttext"	"1"
		"font"		"DefaultMedium"
		"zpos"			"51"
		"noshortcutsyntax"		"1"
	}
	"SurvivorStatsStatus"
	{
		"ControlName"		"Label"
		"fieldName"		"SurvivorStatsStatus"
		"xpos"			"4"
		"ypos"			"31"
		"wide"			"21"
		"tall"			"21"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"	"1"
		"font"		"ink_shadow_9"
		"zpos"			"55"
		"bgcolor_override" ""
	}
	"SurvivorStatsNoAvatarStatus"
	{
		"ControlName"		"Label"
		"fieldName"		"SurvivorStatsNoAvatarStatus"
		"xpos"			"4"
		"ypos"			"31"
		"wide"			"21"
		"tall"			"21"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"	"1"
		"font"		"ink_shadow_9"
		"zpos"			"55"
		"bgcolor_override" ""
	}
	"SurvivorStatsHealth"
	{
		"ControlName"		"HealthPanel"
		"fieldName"		"SurvivorStatsHealth"
		"xpos"		"24"
		"ypos"		"41"
		"wide"		"110"
		"tall"		"12"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"autoresize"	"3"
		"zpos"			"51"
		"monochrome_color"	"Gray"
	}
	"SurvivorSurvivalRecordImage"
	{
		"ControlName"	"CIconPanel"
		"fieldName"		"SurvivorSurvivalRecordImage"
		"xpos"			"216"	[$WIN32]
		"ypos"          "39"	[$WIN32]
		"wide"			"14"
		"tall"			"14"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"
		"icon"			"icon_gold_medal_small"
		"zpos"			"2"
	}
	"SurvivorSurvivalRecord"
	{
		"ControlName"	"Label"
		"fieldName"		"SurvivorSurvivalRecord"
		"xpos"			"57"	[$WIN32]
		"ypos"          "39"	[$WIN32]
		"wide"			"160"
		"tall"			"14"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"00:00.00"
		"textAlignment"	"east"
		"font"			"ink_11"
		"zpos"			"2"
	}
	"PingImage"
	{
		"ControlName"		"Label"
		"fieldName"		"PingImage"
		"font"			"GameUIButtons"
		"labelText"		""
		"textAlignment"	"center"	[$X360]
		"textAlignment"	"east"	[$WIN32]
		"xpos"			"280"	[$X360]
		"xpos"			"2603333"	[$WIN32]
		"ypos"			"24"
		"wide"			"16"
		"tall"			"16"
		"autoResize"	"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"zpos"			"52"
	}
	"PingLabel"	[$WIN32]
	{
		"ControlName"	"Label"
		"fieldName"		"PingLabel"
		"xpos"			"235"
		"ypos"			"27"
		"wide"			"32"
		"tall"			"28"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"0"
		"textAlignment"	"west"
		"font"			"ink_15"
		"zpos"			"2"
	}
	"Voice"
	{
		"ControlName"	"Panel"
		"fieldName"		"Voice"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"1"
	}
	"PlayerBackground"
	{
		"ControlName"	"Panel"
		"fieldName"		"PlayerBackground"
		"xpos"			"26"
		"ypos"			"30"
		"zpos"			"0"
		"wide"			"257"
		"tall"			"27"
		"autoResize"	"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"bgcolor_override"	"0 0 0 220"
	}
	"PlayerBackground_Selected"
	{
		"ControlName"	"Panel"
		"fieldName"		"PlayerBackground_Selected"
		"xpos"			"26"
		"ypos"			"30"
		"zpos"			"0"
		"wide"			"257"
		"tall"			"21"
		"autoResize"	"1"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"	"0"
		"bgcolor_override"	"0 0 0 220"
	}
	"IconForSlot_FirstAid"
		{
		"ControlName"	"CIconPanel"
		"fieldName"		"IconForSlot_FirstAid"
		"xpos"			"134"
		"ypos"			"41"
		"wide"			"11"
		"tall"			"11"
		"visible"		"0"
		"enabled"		"1"
		"zpos"			"2"
		"scaleImage"	"1"
		"icon"			"icon_equip_medkit_small"
	}
	"IconForSlot_Pills"
	{
		"ControlName"	"CIconPanel"
		"fieldName"		"IconForSlot_Pills"
		"xpos"			"145"
		"ypos"			"41"
		"wide"			"11"
		"tall"			"11"
		"visible"		"0"
		"enabled"		"1"
		"zpos"			"2"
		"scaleImage"	"1"
		"icon"			"icon_equip_pills_small"
	}
	"IconForSlot_Grenade"
	{
		"ControlName"	"CIconPanel"
		"fieldName"		"IconForSlot_Grenade"
		"xpos"			"156"
		"ypos"			"41"
		"wide"			"11"
		"tall"			"11"
		"visible"		"0"
		"enabled"		"1"
		"zpos"			"2"
		"scaleImage"	"1"
		"icon"			"icon_equip_pipebomb_small"
	}
}