
"Resource/UI/versusmodescoreboard_tiebreak.res"
{
	"HeaderBackgroundImage"
	{
		"ControlName"	"Panel"
		"fieldName"		"HeaderBackgroundImage"
		"xpos"			"100"
		"wide"			"263"
		"tall"			"20"
		"visible"		"0"
		"enabled"		"1"
		"scaleImage"	"1"
		"bgcolor_override"		"0 0 0 220"
		"src_corner_height"		"16"
		"src_corner_width"		"16"
		"draw_corner_width"		"3"
		"draw_corner_height" 	"3"
	}
	"HeaderBackgroundFill"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"HeaderBackgroundFill"
		"xpos"				"11"
		"ypos"				"13"
		"wide"				"156"
		"tall"				"64"
		"scaleImage"		"1"
		"visible"			"1"
		"enabled"			"1"
		"fillcolor" 		"0 0 0 220"
		"zpos"				"-2"
	}
	"RoundInfoMessage"
	{
		"ControlName"		"Label"
		"fieldName"		"RoundInfoMessage"
		"xpos"		"11"
		"ypos"		"10"
		"wide"		"156"
		"tall"		"26"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#L4D_Scavenge_TieBreaker_Title"
		"textAlignment"		"center"
		"font"		"MenuTitle"
	}
	"CenterBackgroundImage"
	{
		"ControlName"	"Panel"
		"fieldName"		"CenterBackgroundImage"
		"xpos"				"11"
		"ypos"			"35"
		"wide"				"156"
		"tall"			"20"
		"visible"		"0"
		"enabled"		"1"
		"scaleImage"	"1"
		"bgcolor_override"		"0 0 0 220"
	}
	"CenterBackgroundFill"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"CenterBackgroundFill"
		"xpos"				"11"
		"ypos"				"35"
		"wide"				"156"
		"tall"				"20"
		"scaleImage"		"1"
		"visible"			"1"
		"enabled"			"1"
		"fillcolor" 		"0 0 0 220"
		"zpos"				"-2"
	}
	"CenterBackgroundFill2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"CenterBackgroundFill2"
		"xpos"				"11"
		"ypos"				"57"
		"wide"				"156"
		"tall"				"20"
		"scaleImage"		"1"
		"visible"			"1"
		"enabled"			"1"
		"fillcolor" 		"0 0 0 220"
		"zpos"				"-2"
	}
	"TieBreakerMethodLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"TieBreakerMethodLabel"
		"xpos"				"-50"
		"ypos"				"35"
		"wide"				"280"
		"tall"				"20"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"
		"enabled"			"1"
		"labelText"			"#L4D_Versus_TieBreaker_Description"
		"textAlignment"		"center"
		"font"				"PlayerDisplayName"
	}
	"YourTeamLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"YourTeamLabel"
		"xpos"				"15"
		"ypos"				"30"
		"wide"				"200"
		"tall"				"30"
		"visible"			"1"
		"labelText"			"#L4D_Scavenge_YourTeam"
		"textAlignment"		"west"
		"font"				"PlayerDisplayName"
	}
	"EnemyTeamLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"EnemyTeamLabel"
		"xpos"				"15"
		"ypos"				"51"
		"wide"				"200"
		"tall"				"30"
		"visible"			"1"
		"labelText"			"#L4D_Scavenge_Opponent"
		"textAlignment"		"west"
		"font"				"PlayerDisplayName"
	}
	"YourTeamDamage"
	{
		"ControlName"		"Label"
		"fieldName"			"YourTeamDamage"
		"xpos"				"90"
		"ypos"				"30"
		"wide"				"100"
		"tall"				"30"
		"visible"			"1"
		"labelText"			"0"
		"textAlignment"		"west"
		"font"				"MenuTitle"
	}
	"EnemyTeamDamage"
	{
		"ControlName"		"Label"
		"fieldName"			"EnemyTeamDamage"
		"xpos"				"90"
		"ypos"				"51"
		"wide"				"100"
		"tall"				"30"
		"visible"			"1"
		"labelText"			"0"
		"textAlignment"		"west"
		"font"				"MenuTitle"
	}
	"YourTeamBonus5"
	{
		"ControlName"		"Label"
		"fieldName"			"YourTeamBonus"
		"xpos"				"135"
		"ypos"				"30"
		"wide"				"100"
		"tall"				"30"
		"visible"			"1"
		"labelText"			"+ 25"
		"textAlignment"		"west"
		"font"				"MenuTitle"
	}
	"EnemyTeamBonus5"
	{
		"ControlName"		"Label"
		"fieldName"			"EnemyTeamBonus"
		"xpos"				"135"
		"ypos"				"51"
		"wide"				"100"
		"tall"				"30"
		"visible"			"1"
		"labelText"			"+ 25"
		"textAlignment"		"west"
		"font"				"MenuTitle"
	}
}