
"Resource/UI/ReadyCountdown.res"
{
	"ready_countdown"
	{
		"ControlName"	"Frame"
		"fieldName"		"ready_countdown"
		"xpos"			"c-48"
		"ypos"			"68"
		"wide"			"115"
		"tall"			"50"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
	}
	"BackgroundFill"
	{
		"ControlName"	"Panel"
		"fieldName"		"Background"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"43"
		"tall"			"43"
		"visible"			"0"
		"enabled"			"0"
		"scaleImage"	"1"
		"bgcolor_override"		"0 0 0 200"
		"src_corner_height"		"16"
		"src_corner_width"		"16"
		"draw_corner_width"		"3"
		"draw_corner_height" 	"3"
	}
	"BackgroundFill"
	{
		"ControlName"	"Panel"
		"fieldName"		"Background"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"43"
		"tall"			"43"
		"visible"			"0"
		"enabled"			"0"
		"scaleImage"	"1"
		"bgcolor_override"		"0 0 0 220"
		"src_corner_height"		"16"
		"src_corner_width"		"16"
		"draw_corner_width"		"3"
		"draw_corner_height" 	"3"
	}
	"Seconds_1"
	{
		"ControlName"		"Label"
		"fieldName"			"Seconds_1"
		"xpos"				"99999"
		"ypos"				"2"
		"wide"				"75"
		"tall"				"12"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"#L4D_s_team_ready_seconds_1"
		"textAlignment"		"west"
		"font"				"MenuSubTitle"
	}
	"Seconds_2"
	{
		"ControlName"		"Label"
		"fieldName"			"Seconds_2"
		"xpos"				"99999"
		"ypos"				"14"
		"wide"				"75"
		"tall"				"12"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"#L4D_s_team_ready_seconds_2"
		"textAlignment"		"west"
		"font"				"MenuSubTitle"
	}
	"Countdown"
	{
		"ControlName"		"Label"
		"fieldName"			"Countdown"
		"xpos"				"20"
		"ypos"				"-5"
		"wide"				"50"
		"tall"				"50"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			""
		"textAlignment"		"center"
		"font"				"ink_shadow_40"
	}
}