
"Resource/UI/ScavengeModeScoreboard.res"
{
	"RoundInfoBackgroundImage"
	{
		"ControlName"	"ScalableImagePanel"
		"fieldName"		"RoundInfoBackgroundImage"
		"xpos"			"20"
		"ypos"			"30"
		"wide"			"319"
		"tall"			"26"
		"visible"			"0"
		"enabled"			"0"
		"scaleImage"	"1"
		"image"			"../vgui/hud/ScalablePanel_bgBlack50_outlineGrey"
		"drawcolor"		"255 64 64 255"
		"src_corner_height"		"16"
		"src_corner_width"		"16"
		"draw_corner_width"		"3"
		"draw_corner_height" 	"3"
	}
	"RoundInfoBackgroundFill"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"RoundInfoBackgroundFill"
		"xpos"				"29"
		"ypos"				"70"
		"wide"				"319"
		"tall"				"65"
		"scaleImage"		"1"
		"visible"			"0"
		"enabled"			"1"
		"fillcolor" 		"0 0 0 220"
		"zpos"				"-2"
	}
	"RoundInfoMessage"
	{
		"ControlName"		"Label"
		"fieldName"		"RoundInfoMessage"
		"xpos"		"29"
		"ypos"		"31"
		"wide"		"286"
		"tall"		"26"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#L4D_Scavenge_TeamFlip"
		"textAlignment"		"center"
		"font"		"HudAmmoLargeShadow20"
	}
	"CenterBackgroundImage"
	{
		"ControlName"	"ScalableImagePanel"
		"fieldName"		"CenterBackgroundImage"
		"xpos"			"20"
		"ypos"			"57"
		"wide"			"319"
		"tall"			"75"
		"visible"			"0"
		"enabled"			"0"
		"scaleImage"	"1"
		"image"			"../vgui/hud/ScalablePanel_bgBlack50_outlineGrey"
		"drawcolor"		"255 64 64 255"
		"src_corner_height"		"16"
		"src_corner_width"		"16"
		"draw_corner_width"		"3"
		"draw_corner_height" 	"3"
	}
	"CenterBackgroundFill"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"CenterBackgroundFill"
		"xpos"				"29"
		"ypos"				"57"
		"wide"				"319"
		"tall"				"65"
		"scaleImage"		"1"
		"visible"			"1"
		"enabled"			"1"
		"fillcolor" 		"0 0 0 200"
		"zpos"				"-2"
	}
	"CenterBackgroundFill2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"CenterBackgroundFill2"
		"xpos"				"29"
		"ypos"				"79"
		"wide"				"319"
		"tall"				"43"
		"scaleImage"		"1"
		"visible"			"1"
		"enabled"			"1"
		"fillcolor" 		"0 0 0 200"
		"zpos"				"-2"
	}
	"RoundLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"RoundLabel"
		"xpos"		"36"
		"ypos"		"56"
		"wide"		"200"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#L4D_Scavenge_Round_Current"
		"textAlignment"		"west"
		"font"		"PlayerDisplayName"
		"fgcolor_override"	"MediumGray"
	}
	"RoundLimitLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"RoundLimitLabel"
		"xpos"		"100"
		"ypos"		"56"
		"wide"		"200"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#L4D_Scavenge_RoundLimit"
		"textAlignment"		"east"
		"font"		"MenuSubTitle"
		"fgcolor_override"	"MediumGray"
	}
	"RoundTipBackgroundImage"
	{
		"ControlName"	"ScalableImagePanel"
		"fieldName"		"RoundTipBackgroundImage"
		"xpos"			"20"
		"ypos"			"132"
		"wide"			"319"
		"tall"			"26"
		"visible"			"0"
		"enabled"			"0"
		"scaleImage"	"1"
		"image"			"../vgui/hud/ScalablePanel_bgBlack50_outlineGrey"
		"drawcolor"		"255 64 64 255"
		"src_corner_height"		"16"
		"src_corner_width"		"16"
		"draw_corner_width"		"3"
		"draw_corner_height" 	"3"
	}
	"RoundTipBackgroundFill"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"RoundTipBackgroundFill"
		"xpos"				"29"
		"ypos"				"123"
		"wide"				"319"
		"tall"				"26"
		"scaleImage"		"1"
		"visible"			"0"
		"enabled"			"1"
		"fillcolor" 		"0 0 0 200"
		"zpos"				"-2"
	}
	"RoundTipMessage"
	{
		"ControlName"		"Label"
		"fieldName"		"RoundTipMessage"
		"xpos"		"11"
		"ypos"		"123"
		"wide"		"319"
		"tall"		"26"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#L4D_Scavenge_TeamFlip"
		"textAlignment"		"center"
		"font"		"MenuTitle_DropShadow"				[$ENGLISH]
		"font"		"MenuTitle_DropShadow"		[!$ENGLISH]
	}
	"ScoreBackgroundImage"
	{
		"ControlName"	"ScalableImagePanel"
		"fieldName"		"ScoreBackgroundImage"
		"xpos"			"25"
		"ypos"			"70"
		"wide"			"310"
		"tall"			"62"
		"visible"		"0"
		"enabled"		"0"
		"scaleImage"	"1"
		"alpha"			"0"
		"image"			"../vgui/hud/ScalablePanel_bgBlack_outlineRed"
		"zpos"			"10"
		"src_corner_height"		"16"
		"src_corner_width"		"16"
		"draw_corner_width"		"8"
		"draw_corner_height" 	"8"
	}
	"YourTeamLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"YourTeamLabel"
		"xpos"		"36"	[$WIN32]
		"ypos"		"82"	[$WIN32]
		"wide"		"200"
		"tall"		"16"
		"visible"		"1"
		"labelText"		"#L4D_Scavenge_YourTeam"
		"textAlignment"		"west"
		"font"		"PlayerDisplayName"
		"pin_to_sibling"		"XboxIconYourTeam"		[$X360]
		"pin_corner_to_sibling"	"0"						[$X360]
		"pin_to_sibling_corner"	"1"						[$X360]
	}
	"EnemyTeamLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"EnemyTeamLabel"
		"xpos"		"36"	[$WIN32]
		"ypos"		"102"	[$WIN32]
		"wide"		"200"
		"tall"		"16"
		"visible"		"1"
		"labelText"		"#L4D_Scavenge_Opponent"
		"textAlignment"		"west"
		"font"		"PlayerDisplayName"
		"pin_to_sibling"		"XboxIconEnemyTeam"		[$X360]
		"pin_corner_to_sibling"	"0"						[$X360]
		"pin_to_sibling_corner"	"1"						[$X360]
	}
	"Round1Panel"
	{
		"ControlName"	"CScavengeRoundPanel"
		"fieldName"		"Round1Panel"
		"xpos"			"170"
		"ypos"			"79"
		"wide"			"24"
		"tall"			"44"
		"visible"		"1"
		"enabled"		"1"
		"zpos"			"15"
	}
	"Round2Panel"
	{
		"ControlName"	"CScavengeRoundPanel"
		"fieldName"		"Round2Panel"
		"xpos"			"191"
		"ypos"			"79"
		"wide"			"24"
		"tall"			"44"
		"visible"		"1"
		"enabled"		"1"
		"zpos"			"15"
	}
	"Round3Panel"
	{
		"ControlName"	"CScavengeRoundPanel"
		"fieldName"		"Round3Panel"
		"xpos"			"212"
		"ypos"			"79"
		"wide"			"24"
		"tall"			"44"
		"visible"		"1"
		"enabled"		"1"
		"zpos"			"15"
	}
	"Round4Panel"
	{
		"ControlName"	"CScavengeRoundPanel"
		"fieldName"		"Round4Panel"
		"xpos"			"233"
		"ypos"			"79"
		"wide"			"24"
		"tall"			"44"
		"visible"		"1"
		"enabled"		"1"
		"zpos"			"15"
	}
	"Round5Panel"
	{
		"ControlName"	"CScavengeRoundPanel"
		"fieldName"		"Round5Panel"
		"xpos"			"254"
		"ypos"			"79"
		"wide"			"24"
		"tall"			"44"
		"visible"		"1"
		"enabled"		"1"
		"zpos"			"15"
	}
	"FinalScorePanel"
	{
		"ControlName"	"CScavengeRoundPanel"
		"fieldName"		"FinalScorePanel"
		"xpos"			"275"
		"ypos"			"79"
		"wide"			"24"
		"tall"			"44"
		"visible"		"1"
		"enabled"		"1"
		"zpos"			"15"
	}
	"SplatterTopLeft"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"SplatterTopLeft"
		"xpos"				"0"
		"ypos"				"10"
		"wide"				"100"
		"tall"				"60"
		"scaleImage"		"1"
		"visible"			"0"
		"enabled"			"0"
		"image"				"../vgui/hud/splatter1"
		"drawColor"			"64 64 64 255"
		"zpos"				"-3"
	}
	"SplatterBottomLeft"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"SplatterBottomLeft"
		"xpos"				"-5"
		"ypos"				"105"
		"wide"				"80"
		"tall"				"80"
		"scaleImage"		"1"
		"visible"			"0"
		"enabled"			"0"
		"image"				"../vgui/hud/splatter3"
		"drawColor"			"64 64 64 255"
		"zpos"				"-3"
	}
	"SplatterTopRight"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"SplatterTopRight"
		"xpos"				"276"
		"ypos"				"-6"
		"wide"				"80"
		"tall"				"80"
		"scaleImage"		"1"
		"visible"			"0"
		"enabled"			"0"
		"image"				"../vgui/hud/splatter_corner_upper_right"
		"drawColor"			"64 64 64 255"
		"zpos"				"-3"
	}
	"SplatterBottom"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"SplatterBottom"
		"xpos"				"193"
		"ypos"				"158"
		"wide"				"110"
		"tall"				"30"
		"scaleImage"		"1"
		"visible"			"0"
		"enabled"			"0"
		"image"				"../vgui/hud/splatter_horizontal_bottom"
		"drawColor"			"64 64 64 255"
		"zpos"				"-3"
	}
}