"Resource/UI/HUD/TeammatePanel_Incap.res"
{
	"BackgroundImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"BackgroundImage"
		"xpos"			"10"
		"ypos"			"32"
		"wide"			"27"
		"tall"			"27"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"
		"zpos"			"5"
	}
	"Voice"
	{
		"ControlName"	"TeamDisplayVoicePanel"
		"fieldName"		"Voice"
		"xpos"			"28"
		"ypos"			"25"
		"wide"			"16"
		"tall"			"16"
		"visible"		"0"
		"enabled"		"1"
		"zpos"			"100"
		"voice_icon"	"voice_player"
	}
	"Head"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"Head"
		"xpos"			"10"
		"ypos"			"32"
		"wide"			"27"
		"tall"			"27"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"
		"zpos"			"5"
	}
	"Health"
	{
		"ControlName"	"HealthPanel"
		"fieldName"		"Health"
		"xpos"			"35"
		"ypos"			"48"
		"wide"			"91"
		"tall"			"12"
		"visible"		"1"
		"enabled"		"1"
		"zpos"			"-2"
	}
	"HealthNumber"
	{
		"ControlName"	"Label"
		"fieldName"		"HealthNumber"
		"xpos"			"37"
		"ypos"			"32"
		"wide"			"31"
		"tall"			"18"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%HealthNumber%"
		"textAlignment"	"center"
		"font"			"ink_weight_19"
		"zpos"			"7"
	}
	"Name"
	{
		"ControlName"	"Label"
		"fieldName"		"Name"
		"xpos"			"11"
		"ypos"			"58"
		"wide"			"150"
		"tall"			"11"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"west"
		"font"			"ink_10"
		"zpos"			"33"
		"fgcolor_override" "MediumGray"
	}
	"SurvivorBackground"
	{
		"ControlName"	"Panel"
		"fieldName"		"SurvivorBackground"
		"xpos"			"10"
		"ypos"          "32"
		"wide"			"113"
		"tall"			"37"
		"visible"		"1"
		"enabled"		"1"
		"bgcolor_override"	"0 0 0 90"
		"zpos"			"-5"
	}
}