"Resource/HudLayout.res"
{
    "CustomCrosshair"
    {
        "ControlName"        "ImagePanel"
        "fieldName"          "CustomCrosshair"
        "xpos"               "c-8"
        "ypos"               "c-8"
        "wide"               "16"
        "tall"               "16"
        "visible"            "1"
        "enabled"            "1"
        "scaleImage"         "0"
        "image"              "_crosshair\\crosshair"
        "zpos"               "-100"
        "__description__"    "None"
    }
    "CrosshairDebugBackground"
    {
        "ControlName"        "Panel"
        "fieldName"          "CrosshairDebugBackground"
        "xpos"               "c-32"
        "ypos"               "c-32"
        "wide"               "64"
        "tall"               "64"
        "visible"            "0"
        "enabled"            "1"
        "zpos"               "-2000"
        "bgcolor_override"   "TransparentLightBlack"
        "__description__"    "None"
    }
    "HudWeaponSelection"
    {
        "fieldName"          "HudWeaponSelection"
        "xpos"               "r197"
        "ypos"               "c95"
        "wide"               "200"
        "tall"               "175"
        "visible"            "1"
        "enabled"            "1"
        "usetitlesafe"       "1"
        "if_split_screen_horizontal"
        {
            "ypos"               "0"
        }
        "LargeBoxWide"       "150"
        "LargeBoxTall"       "32"
        "SmallBoxWide"       "150"
        "SmallBoxTall"       "24"
        "BoxGap"             "1"
        "BoxDirection"       "0"
        "SelectionNumberXPos" "0"
        "SelectionNumberYPos" "0"
        "SelectionGrowTime"  "0"
        "Ammo1XPos"          "0"
        "Ammo1YPos"          "0"
        "Ammo2XPos"          "0"
        "Ammo2YPos"          "0"
        "IconXPos"           "0"
        "IconYPos"           "0"
        "IconYPos_lodef"     "0"
        "TextYPos"           "0"
        "TextColor"          "0"
        "MaxSlots"           "0"
        "PlaySelectSounds"   "0"
        "PrimaryWeaponsYPos" "10"
        "PrimaryWeaponBoxWide" "70"
        "PrimaryWeaponBoxTall" "34"
        "MeleeWeaponX"       "-26"
        "MeleeWeaponY"       "2"
        "MeleeWeaponWide"    "49"
        "MeleeWeaponTall"    "22"
        "ChainsawX"          "-38"
        "ChainsawY"          "2"
        "ChainsawWide"       "41"
        "ChainsawTall"       "19"
        "ChainsawBarX"       "8"
        "ChainsawBarY"       "5"
        "ChainsawBarWide"    "5"
        "ChainsawBarTall"    "16"
        "PrimaryAmmoXPos"    "26"
        "PrimaryAmmoYPos"    "-8"
        "ReserveAmmoXPos"    "65"
        "ReserveAmmoYPos"    "18"
        "AmmoIconXPos"       "60"
        "AmmoIconYPos"       "21"
        "AmmoIconSize"       "19"
        "SpecialAmmoXPos"    "31"
        "SpecialAmmoYPos"    "12"
        "PrimaryWeaponWide"  "10"
        "PrimaryWeaponTall"  "25"
        "PrimaryBindingYPos" "0"
        "PistolBoxWide"      "21"
        "PistolBoxTall"      "21"
        "RightSideIndent"    "10"
        "IconSize"           "21"
        "PrimaryAmmoFont"    "ink_shadow_64"
        "ReserveAmmoFont"    "ink_25"
        "PistolAmmoFont"     "ink_25"
        "SelectedItemColor"  "255 255 255 255"
        "UnselectedItemColor" "255 255 255 255"
        "SelectedReserveAmmoColor" "255 255 255 100"
        "UnselectedReserveAmmoColor" "255 255 255 100"
        "InactiveItemColor"  "0 0 0 0"
        "SelectedScale"      "1.0"
        "__description__"    "None"
    }
    "CHudLocalPlayerDisplay"
    {
        "fieldName"          "CHudLocalPlayerDisplay"
        "visible"            "1"
        "enabled"            "1"
        "usetitlesafe"       "1"
        "xpos"               "0"
        "ypos"               "99"
        "wide"               "f0"
        "tall"               "f0"
        "if_split_screen_left"
        {
            "xpos"               "0"
        }
        "if_split_screen_top"
        {
            "ypos"               "r90"
        }
        "__description__"    "None"
    }
    "HudZombiePanel"
    {
        "fieldName"          "HudZombiePanel"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "0"
        "ypos"               "c30"
        "wide"               "f0"
        "tall"               "155"
        "PaintBackgroundType" "2"
        "if_split_screen_horizontal"
        {
            "ypos"               "c-45"
        }
        "if_split_screen_left"
        {
            "xpos"               "c-145"
        }
        "if_split_screen_right"
        {
            "xpos"               "c-175"
        }
        "__description__"    "None"
    }
    "HudZombieHealth"
    {
        "fieldName"          "HudZombieHealth"
        "xpos"               "r400"
        "ypos"               "r135"
        "wide"               "400"
        "tall"               "150"
        "visible"            "1"
        "enabled"            "1"
        "usetitlesafe"       "1"
        "if_split_screen_left"
        {
            "xpos"               "1"
        }
        "__description__"    "None"
    }
    "CHudAbilityTimer"
    {
        "ControlName"        "CHudAbilityTimer"
        "fieldName"          "CHudAbilityTimer"
        "xpos"               "r86"
        "ypos"               "r95"
        "wide"               "80"
        "tall"               "70"
        "visible"            "1"
        "enabled"            "1"
        "ability_surpressed_color" "127 127 127 255"
        "ability_charging_color" "127 127 127 255"
        "ability_ready_color" "255 255 255 255"
        "usetitlesafe"       "1"
        "if_split_screen_left"
        {
            "xpos"               "-8"
        }
        "__description__"    "None"
    }
    "CHudZombieTeamDisplay"
    {
        "fieldName"          "CHudZombieTeamDisplay"
        "visible"            "1"
        "enabled"            "1"
        "usetitlesafe"       "1"
        "xpos"               "-18"
        "ypos"               "r91"
        "wide"               "f0"
        "tall"               "100"
        "VertPanelSpacing"   "45"
        "HorizPanelSpacing"  "140"
        "if_split_screen_horizontal"
        {
            "ypos"               "c-59"
        }
        "if_split_screen_vertical"
        {
            "xpos"               "c-140"
        }
        "__description__"    "None"
    }
    "HudGhostPanel"
    {
        "fieldName"          "HudGhostPanel"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "0"
        "ypos"               "c30"
        "wide"               "f0"
        "tall"               "155"
        "WhiteText"          "192 192 192 255"
        "RedText"            "246 5 5 255"
        "padding"            "4"
        "bgcolor_override"   "0 0 0 0"
        "if_split_screen_horizontal"
        {
            "ypos"               "c-45"
        }
        "if_split_screen_left"
        {
            "xpos"               "c-145"
        }
        "if_split_screen_right"
        {
            "xpos"               "c-205"
        }
        "__description__"    "None"
    }
    "HudPZDamageRecord"
    {
        "fieldName"          "HudPZDamageRecord"
        "xpos"               "-5"
        "ypos"               "50"
        "wide"               "f20"
        "tall"               "90"
        "visible"            "1"
        "enabled"            "1"
        "PaintBackgroundType" "2"
        "usetitlesafe"       "1"
        "label_textalign"    "west"
        "if_split_screen_horizontal"
        {
            "ypos"               "20"
            "label_textalign"    "west"
        }
        "if_split_screen_vertical"
        {
            "ypos"               "20"
            "label_textalign"    "center"
        }
        "__description__"    "None"
    }
    "CHudTeamDisplay"
    {
        "fieldName"          "CHudTeamDisplay"
        "visible"            "1"
        "enabled"            "1"
        "usetitlesafe"       "1"
        "xpos"               "6"
        "ypos"               "r165"
        "wide"               "f0"
        "tall"               "250"
        "if_split_screen_horizontal"
        {
            "ypos"               "c-59"
        }
        "if_split_screen_vertical"
        {
            "xpos"               "c-300"
            "wide"               "600"
            "tall"               "100"
            "usetitlesafe"       "1"
        }
        "__description__"    "None"
    }
    "PZEndGamePanel"
    {
        "fieldName"          "PZEndGamePanel"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "c-377"
        "ypos"               "c10"
        "wide"               "354"
        "tall"               "200"
        "__description__"    "None"
    }
    "CHudVote"
    {
        "fieldName"          "CHudVote"
        "xpos"               "-3"
        "ypos"               "c-260"
        "tall"               "200"
        "visible"            "1"
        "enabled"            "1"
        "bgcolor_override"   "0 0 0 0"
        "PaintBackgroundType" "0"
        "usetitlesafe"       "1"
        "__description__"    "None"
    }
    "HudScavengeProgress"
    {
        "fieldName"          "HudScavengeProgress"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "c-45"
        "ypos"               "5"
        "zpos"               "0"
        "wide"               "85"
        "tall"               "43"
        "PaintBackground"    "0"
        "NumberFont"         "HudNumbers"
        "__description__"    "None"
    }
    "HudSurvivalTimer"
    {
        "fieldName"          "HudSurvivalTimer"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "c-225"
        "ypos"               "-42"
        "zpos"               "0"
        "wide"               "350"
        "tall"               "100"
        "PaintBackground"    "0"
        "NumberFont"         "HudNumbers"
        "__description__"    "None"
    }
    "HudScavengeTimer"
    {
        "fieldName"          "HudScavengeTimer"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "c-225"
        "ypos"               "3"
        "zpos"               "0"
        "wide"               "440"
        "tall"               "100"
        "PaintBackground"    "0"
        "NumberFont"         "HudNumbers"
        "__description__"    "None"
    }
    "overview"
    {
        "fieldname"          "overview"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "0"
        "ypos"               "480"
        "wide"               "0"
        "tall"               "0"
        "__description__"    "None"
    }
    "HudCommentary"
    {
        "fieldName"          "HudCommentary"
        "xpos"               "c-190"
        "ypos"               "350"
        "wide"               "380"
        "tall"               "40"
        "visible"            "0"
        "enabled"            "1"
        "alpha"              "0"
        "PaintBackgroundType" "2"
        "bar_xpos"           "50"
        "bar_ypos"           "20"
        "bar_height"         "8"
        "bar_width"          "320"
        "speaker_xpos"       "50"
        "speaker_ypos"       "8"
        "count_xpos_from_right" "10"
        "count_ypos"         "8"
        "icon_texture"       "vgui/hud/icon_commentary"
        "icon_xpos"          "0"
        "icon_ypos"          "0"
        "icon_width"         "40"
        "icon_height"        "40"
        "__description__"    "None"
    }
    "HudHDRDemo"
    {
        "fieldName"          "HudHDRDemo"
        "xpos"               "0"
        "ypos"               "0"
        "wide"               "640"
        "tall"               "480"
        "visible"            "0"
        "enabled"            "1"
        "Alpha"              "255"
        "PaintBackgroundType" "2"
        "BorderColor"        "0 0 0 255"
        "BorderLeft"         "16"
        "BorderRight"        "16"
        "BorderTop"          "16"
        "BorderBottom"       "64"
        "BorderCenter"       "0"
        "TextColor"          "255 255 255 255"
        "LeftTitleY"         "422"
        "RightTitleY"        "422"
        "__description__"    "None"
    }
    "TargetID"
    {
        "fieldName"          "TargetID"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "c-320"
        "ypos"               "c-240"
        "wide"               "640"
        "tall"               "480"
        "__description__"    "None"
    }
    "PlayerLabel"
    {
        "fieldName"          "PlayerLabel"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "c-320"
        "ypos"               "c-240"
        "wide"               "640"
        "tall"               "480"
        "__description__"    "None"
    }
    "HudArmor"
    {
        "fieldName"          "HudArmor"
        "xpos"               "156"
        "ypos"               "440"
        "wide"               "132"
        "tall"               "40"
        "visible"            "1"
        "enabled"            "1"
        "PaintBackgroundType" "2"
        "icon_xpos"          "0"
        "icon_ypos"          "2"
        "digit_xpos"         "34"
        "digit_ypos"         "2"
        "__description__"    "None"
    }
    "HudSuit"
    {
        "fieldName"          "HudSuit"
        "xpos"               "140"
        "ypos"               "432"
        "wide"               "108"
        "tall"               "36"
        "visible"            "1"
        "enabled"            "1"
        "PaintBackgroundType" "2"
        "text_xpos"          "8"
        "text_ypos"          "20"
        "digit_xpos"         "50"
        "digit_ypos"         "2"
        "__description__"    "None"
    }
    "HudProgressBar"
    {
        "fieldName"          "HudProgressBar"
        "xpos"               "c-114"
        "ypos"               "c10"
        "if_split_screen_vertical"
        {
            "ypos"               "c-10"
        }
        "wide"               "300"
        "tall"               "80"
        "visible"            "1"
        "enabled"            "1"
        "PaintBackgroundType" "0"
        "PaintBackground"    "0"
        "__description__"    "None"
    }
    "HudRoundTimer"
    {
        "fieldName"          "HudRoundTimer"
        "xpos"               "c-20"
        "ypos"               "440"
        "wide"               "120"
        "tall"               "40"
        "visible"            "1"
        "enabled"            "1"
        "PaintBackgroundType" "2"
        "FlashColor"         "HudIcon_Red"
        "icon_xpos"          "0"
        "icon_ypos"          "2"
        "digit_xpos"         "34"
        "digit_ypos"         "2"
        "__description__"    "None"
    }
    "HudAccount"
    {
        "fieldName"          "HudAccount"
        "xpos"               "r134"
        "ypos"               "374"
        "wide"               "116"
        "tall"               "80"
        "visible"            "1"
        "enabled"            "1"
        "PaintBackgroundType" "2"
        "icon_xpos"          "0"
        "icon_ypos"          "36"
        "digit_xpos"         "104"
        "digit_ypos"         "36"
        "icon2_xpos"         "0"
        "icon2_ypos"         "2"
        "digit2_xpos"        "104"
        "digit2_ypos"        "2"
        "__description__"    "None"
    }
    "HudShoppingCart"
    {
        "fieldName"          "HudShoppingCart"
        "xpos"               "16"
        "ypos"               "200"
        "wide"               "40"
        "tall"               "40"
        "visible"            "1"
        "enabled"            "1"
        "PaintBackgroundType" "2"
        "IconColor"          "HudIcon_Green"
        "__description__"    "None"
    }
    "HudC4"
    {
        "fieldName"          "HudC4"
        "xpos"               "16"
        "ypos"               "248"
        "wide"               "40"
        "tall"               "40"
        "visible"            "1"
        "enabled"            "1"
        "PaintBackgroundType" "2"
        "IconColor"          "HudIcon_Green"
        "FlashColor"         "HudIcon_Red"
        "__description__"    "None"
    }
    "HudDefuser"
    {
        "fieldName"          "HudDefuser"
        "xpos"               "16"
        "ypos"               "248"
        "wide"               "40"
        "tall"               "40"
        "visible"            "1"
        "enabled"            "1"
        "PaintBackgroundType" "2"
        "IconColor"          "HudIcon_Green"
        "__description__"    "None"
    }
    "HudHostageRescueZone"
    {
        "fieldName"          "HudHostageRescueZone"
        "xpos"               "16"
        "ypos"               "248"
        "wide"               "40"
        "tall"               "40"
        "visible"            "1"
        "enabled"            "1"
        "PaintBackgroundType" "2"
        "IconColor"          "HudIcon_Green"
        "FlashColor"         "HudIcon_Red"
        "__description__"    "None"
    }
    "HudScenarioIcon"
    {
        "fieldName"          "HudScenarioIcon"
        "xpos"               "c110"
        "ypos"               "443"
        "wide"               "40"
        "tall"               "44"
        "visible"            "1"
        "enabled"            "1"
        "PaintBackgroundType" "2"
        "IconColor"          "Hostage_Yellow"
        "__description__"    "None"
    }
    "HudFlashlight"
    {
        "fieldName"          "HudFlashlight"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "16"
        "ypos"               "370"
        "wide"               "102"
        "tall"               "20"
        "text_xpos"          "8"
        "text_ypos"          "6"
        "TextColor"          "255 170 0 220"
        "PaintBackgroundType" "2"
        "__description__"    "None"
    }
    "HudDamageIndicator"
    {
        "fieldName"          "HudDamageIndicator"
        "visible"            "1"
        "enabled"            "1"
        "MinimumWidth"       "40"
        "MaximumWidth"       "80"
        "StartRadius"        "120"
        "EndRadius"          "80"
        "MinimumHeight"      "30"
        "MaximumHeight"      "60"
        "MinimumTime"        "2"
        "DmgColorLeft"       "255 0 0 0"
        "DmgColorRight"      "255 0 0 0"
        "dmg_xpos"           "30"
        "dmg_ypos"           "100"
        "dmg_wide"           "36"
        "dmg_tall1"          "240"
        "dmg_tall2"          "200"
        "__description__"    "None"
    }
    "HudZoom"
    {
        "fieldName"          "HudZoom"
        "visible"            "1"
        "enabled"            "1"
        "Circle1Radius"      "66"
        "Circle2Radius"      "74"
        "DashGap"            "16"
        "DashHeight"         "4"
        "BorderThickness"    "88"
        "__description__"    "None"
    }
    "HudCrosshair"
    {
        "fieldName"          "HudCrosshair"
        "visible"            "1"
        "enabled"            "1"
        "wide"               "640"
        "tall"               "480"
        "ability_size"       "17"
        "ability_surpressed_color" "127 127 127 255"
        "ability_charging_color" "127 127 127 255"
        "ability_ready_color" "255 255 255 255"
        "__description__"    "None"
    }
    "HudDeathNotice"
    {
        "fieldName"          "HudDeathNotice"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "0"
        "ypos"               "0"
        "wide"               "f0"
        "tall"               "480"
        "MaxDeathNotices"    "6"
        "IconSize"           "16"
        "TextFont"           "Default"
        "__description__"    "None"
    }
    "HudVehicle"
    {
        "fieldName"          "HudVehicle"
        "visible"            "1"
        "enabled"            "1"
        "wide"               "640"
        "tall"               "480"
        "__description__"    "None"
    }
    "CVProfPanel"
    {
        "fieldName"          "CVProfPanel"
        "visible"            "1"
        "enabled"            "1"
        "wide"               "640"
        "tall"               "480"
        "__description__"    "None"
    }
    "ScorePanel"
    {
        "fieldName"          "ScorePanel"
        "visible"            "1"
        "enabled"            "1"
        "wide"               "640"
        "tall"               "480"
        "__description__"    "None"
    }
    "HudTrain"
    {
        "fieldName"          "HudTrain"
        "visible"            "1"
        "enabled"            "1"
        "wide"               "640"
        "tall"               "480"
        "__description__"    "None"
    }
    "HudMOTD"
    {
        "fieldName"          "HudMOTD"
        "visible"            "1"
        "enabled"            "1"
        "wide"               "640"
        "tall"               "480"
        "__description__"    "None"
    }
    "HudMessage"
    {
        "fieldName"          "HudMessage"
        "visible"            "1"
        "enabled"            "1"
        "wide"               "640"
        "tall"               "480"
        "__description__"    "None"
    }
    "HudMenu"
    {
        "fieldName"          "HudMenu"
        "visible"            "1"
        "enabled"            "1"
        "wide"               "640"
        "tall"               "480"
        "zpos"               "1"
        "TextFont"           "Default"
        "ItemFont"           "Default"
        "ItemFontPulsing"    "Default"
        "__description__"    "None"
    }
    "HudCloseCaption"
    {
        "fieldName"          "HudCloseCaption"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "c-150"
        "ypos"               "r220"
        "wide"               "300"
        "tall"               "135"
        "usetitlesafe"       "1"
        "if_split_screen_vertical"
        {
            "ypos"               "r160"
            "tall"               "108"
        }
        "if_split_screen_horizontal"
        {
            "xpos"               "0"
            "ypos"               "r220"
            "wide"               "275"
            "tall"               "108"
        }
        "BgAlpha"            "128"
        "GrowTime"           "0.25"
        "ItemHiddenTime"     "0.2"
        "ItemFadeInTime"     "0.15"
        "ItemFadeOutTime"    "0.3"
        "topoffset"          "0"
        "__description__"    "None"
    }
    "HudHistoryResource"
    {
        "fieldName"          "HudHistoryResource"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "r640"
        "wide"               "640"
        "tall"               "330"
        "history_gap"        "55"
        "__description__"    "None"
    }
    "HudGeiger"
    {
        "fieldName"          "HudGeiger"
        "visible"            "1"
        "enabled"            "1"
        "wide"               "640"
        "tall"               "480"
        "__description__"    "None"
    }
    "HUDQuickInfo"
    {
        "fieldName"          "HUDQuickInfo"
        "visible"            "1"
        "enabled"            "1"
        "wide"               "640"
        "tall"               "480"
        "__description__"    "None"
    }
    "HudWeapon"
    {
        "fieldName"          "HudWeapon"
        "visible"            "1"
        "enabled"            "1"
        "wide"               "640"
        "tall"               "480"
        "__description__"    "None"
    }
    "HudAnimationInfo"
    {
        "fieldName"          "HudAnimationInfo"
        "visible"            "1"
        "enabled"            "1"
        "wide"               "640"
        "tall"               "480"
        "__description__"    "None"
    }
    "CBudgetPanel"
    {
        "fieldName"          "CBudgetPanel"
        "visible"            "1"
        "enabled"            "1"
        "wide"               "640"
        "tall"               "480"
        "__description__"    "None"
    }
    "CTextureBudgetPanel"
    {
        "fieldName"          "CTextureBudgetPanel"
        "visible"            "1"
        "enabled"            "1"
        "wide"               "640"
        "tall"               "480"
        "__description__"    "None"
    }
    "HudPredictionDump"
    {
        "fieldName"          "HudPredictionDump"
        "visible"            "1"
        "enabled"            "1"
        "wide"               "640"
        "tall"               "480"
        "__description__"    "None"
    }
    "HudScope"
    {
        "fieldName"          "HudZoom"
        "visible"            "1"
        "enabled"            "1"
        "wide"               "640"
        "tall"               "480"
        "__description__"    "None"
    }
    "HudVoiceSelfStatus"
    {
        "fieldName"          "HudVoiceSelfStatus"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "r132"
        "ypos"               "r78"
        "wide"               "24"
        "tall"               "24"
        "usetitlesafe"       "1"
        "if_split_screen_left"
        {
            "xpos"               "100"
        }
        "__description__"    "None"
    }
    "HudBiofeedback"
    {
        "fieldName"          "HudBiofeedback"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "r128"
        "ypos"               "r479"
        "wide"               "128"
        "tall"               "64"
        "usetitlesafe"       "1"
        "__description__"    "None"
    }
    "HudVoiceStatus"
    {
        "fieldName"          "HudVoiceStatus"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "r130"
        "ypos"               "0"
        "wide"               "150"
        "tall"               "290"
        "item_tall"          "15"
        "item_wide"          "120"
        "item_spacing"       "2"
        "icon_ypos"          "0"
        "icon_xpos"          "0"
        "icon_tall"          "16"
        "icon_wide"          "16"
        "text_xpos"          "18"
        "text_font"          "DefaultDropShadow"
        "inverted"           "0"
        "__description__"    "None"
    }
    "HudFlashbang"
    {
        "__description__"    "None"
    }
    "HudHintDisplay"
    {
        "fieldName"          "HudHintDisplay"
        "visible"            "0"
        "enabled"            "1"
        "xpos"               "c-200"
        "ypos"               "294"
        "wide"               "400"
        "tall"               "50"
        "text_xpos"          "8"
        "text_ypos"          "8"
        "center_x"           "0"
        "center_y"           "-1"
        "__description__"    "None"
    }
    "HudHintKeyDisplay"
    {
        "fieldName"          "HudHintKeyDisplay"
        "visible"            "0"
        "enabled"            "1"
        "xpos"               "r120"
        "ypos"               "r340"
        "wide"               "100"
        "tall"               "200"
        "text_xpos"          "8"
        "text_ypos"          "8"
        "text_xgap"          "8"
        "text_ygap"          "8"
        "TextColor"          "255 170 0 220"
        "PaintBackgroundType" "2"
        "__description__"    "None"
    }
    "HudTerritory"
    {
        "fieldName"          "HudTerritory"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "240"
        "ypos"               "432"
        "wide"               "240"
        "tall"               "48"
        "__description__"    "None"
    }
    "TerritorySCore"
    {
        "fieldName"          "TerritoryScore"
        "visible"            "0"
        "enabled"            "0"
        "xpos"               "240"
        "ypos"               "450"
        "wide"               "200"
        "tall"               "200"
        "text_xpos"          "8"
        "text_ypos"          "4"
        "__description__"    "None"
    }
    "HudChat"
    {
        "ControlName"        "EditablePanel"
        "fieldName"          "HudChat"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "10"
        "ypos"               "275"
        "wide"               "320"
        "tall"               "120"
        "PaintBackgroundType" "2"
        "usetitlesafe"       "1"
        "__description__"    "None"
    }
    "HudMessagePanel"
    {
        "fieldName"          "HudMessagePanel"
        "visible"            "0"
        "enabled"            "1"
        "xpos"               "120"
        "ypos"               "r235"
        "wide"               "400"
        "tall"               "180"
        "PaintBackgroundType" "2"
        "text_xpos"          "4"
        "text_ypos"          "4"
        "text_spacing"       "1"
        "__description__"    "None"
    }
    "HudBlood"
    {
        "fieldName"          "HudBlood"
        "visible"            "1"
        "enabled"            "1"
        "wide"               "640"
        "tall"               "480"
        "__description__"    "None"
    }
    "CHudSurvivorTeamStatus"
    {
        "ControlName"        "CHudSurvivorTeamStatus"
        "fieldName"          "CHudSurvivorTeamStatus"
        "xpos"               "r85"
        "ypos"               "120"
        "wide"               "80"
        "tall"               "20"
        "visible"            "1"
        "enabled"            "1"
        "PaintBackgroundType" "2"
        "__description__"    "None"
    }
    "HudFinaleMeter"
    {
        "fieldName"          "HudFinaleMeter"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "c-100"
        "ypos"               "12"
        "wide"               "200"
        "tall"               "20"
        "PaintBackgroundType" "2"
        "__description__"    "None"
    }
    "HudFrustrationMeter"
    {
        "fieldName"          "HudFrustrationMeter"
        "xpos"               "10"
        "ypos"               "c0"
        "wide"               "300"
        "tall"               "84"
        "visible"            "1"
        "enabled"            "1"
        "PaintBackgroundType" "0"
        "usetitlesafe"       "2"
        "__description__"    "None"
    }
    "HudInfectedVOIP"
    {
        "fieldName"          "HudInfectedVOIP"
        "xpos"               "r130"
        "ypos"               "c100"
        "wide"               "120"
        "tall"               "84"
        "visible"            "1"
        "enabled"            "1"
        "PaintBackgroundType" "0"
        "usetitlesafe"       "2"
        "__description__"    "None"
    }
    "HudCredits"
    {
        "fieldName"          "HudCredits"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "c-270"
        "ypos"               "c-190"
        "wide"               "540"
        "tall"               "380"
        "__description__"    "None"
    }
    "HudAnnouncement"
    {
        "fieldName"          "HudAnnouncement"
        "xpos"               "c-150"
        "ypos"               "300"
        "wide"               "300"
        "tall"               "15"
        "visible"            "0"
        "enabled"            "1"
        "PaintBackgroundType" "2"
        "__description__"    "None"
    }
    "CHudTeamMateInPerilNotice"
    {
        "fieldName"          "CHudTeamMateInPerilNotice"
        "ypos"               "50"
        "visible"            "1"
        "enabled"            "1"
        "__description__"    "None"
    }
    "HudIntensityGraph"
    {
        "fieldName"          "HudIntensityGraph"
        "xpos"               "r75"
        "ypos"               "190"
        "wide"               "70"
        "tall"               "100"
        "visible"            "1"
        "enabled"            "1"
        "PaintBackgroundType" "2"
        "__description__"    "None"
    }
    "HudLeavingAreaWarning"
    {
        "fieldName"          "HudLeavingAreaWarning"
        "xpos"               "10"
        "ypos"               "c26"
        "wide"               "200"
        "tall"               "14"
        "visible"            "1"
        "enabled"            "1"
        "PaintBackgroundType" "2"
        "usetitlesafe"       "2"
        "__description__"    "None"
    }
    "CItemPickupPanel"
    {
        "fieldName"          "CItemPickupPanel"
        "xpos"               "0"
        "ypos"               "0"
        "wide"               "f0"
        "tall"               "f0"
        "visible"            "1"
        "enabled"            "1"
        "PaintBackgroundType" "2"
        "usetitlesafe"       "0"
        "__description__"    "None"
    }
    "StatsCrawl"
    {
        "fieldName"          "StatsCrawl"
        "visible"            "1"
        "enabled"            "1"
        "xpos"               "0"
        "ypos"               "0"
        "wide"               "f0"
        "tall"               "f0"
        "vote_bot_inset_x"   "90"
        "vote_bot_inset_y"   "45"
        "skip_legend_inset_x" "10"
        "skip_legend_inset_y" "25"
        "SkipLabelFont"      "DefaultLarge"
        "ButtonFont"         "GameUIButtons"
        "StatsCrawlFont"     "OuttroStatsCrawl"
        "StatsCrawlUnderlineFont" "OuttroStatsCrawlUnderline"
        "CreditsCrawlFont"   "Credits"
        "votes"
        {
            "box_size"           "16"
            "spacer"             "4"
            "box_inset"          "1"
        }
        "__description__"    "None"
    }
}