
"Resource/UI/HUD/HudScavengeProgress.res"
{
	"ProgressBackground"
	{
		"ControlName"	"ScalableImagePanel"
		"fieldName"		"ProgressBackground"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"85"
		"tall"			"43"
		"visible"		"0"
		"enabled"		"1"
		"scaleImage"	"1"
		"image"			"../vgui/hud/ScalablePanel_bgMidGrey_glow"
		"zpos"			"-1"
		"src_corner_height"		"16"
		"src_corner_width"		"16"
		"draw_corner_width"		"5"
		"draw_corner_height" 	"5"
	}
	"GasCanImage"
	{
		"ControlName"		"CIconPanel"
		"fieldName"			"GasCanImage"
		"xpos"				"3"
		"ypos"				"7"
		"wide"				"30"
		"tall"				"30"
		"scaleImage"		"0"
		"visible"			"0"
		"enabled"			"1"
		"icon"				"icon_gas_can"
	}
	"ItemsCollectedDigits"
	{
		"ControlName"	"Label"
		"fieldName"		"ItemsCollectedDigits"
		"xpos"			"11"
		"ypos"			"-3"
		"zpos"			"1"
		"wide"			"42"
		"tall"			"42"
		"visible"		"1"
		"labelText"		"0"
		"textAlignment"	"east"
		"font"			"ink_shadow_40"
	}
	"ItemDigitDivider"
	{
		"ControlName"	"Label"
		"fieldName"		"ItemsRemainingLabel"
		"xpos"			"49"
		"ypos"			"9"
		"wide"			"12"
		"tall"			"24"
		"visible"		"1"
		"labelText"		"/"
		"textAlignment"	"south"
		"font"			"ink_shadow_11"
	}
	"ItemsGoalDigits"
	{
		"ControlName"	"Label"
		"fieldName"		"ItemsGoalDigits"
		"xpos"			"58"
		"ypos"			"9"
		"wide"			"24"
		"tall"			"24"
		"visible"		"1"
		"labelText"		"0"
		"textAlignment"	"south-west"
		"font"			"ink_shadow_11"
	}
}