"Resource/UI/HUD/PZDamageRecordPanel.res"
{
	"recordlabel1"
	{
		"ControlName"	"Label"
		"fieldName"		"recordlabel1"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f40"
		"tall"			"15"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"RB saved coach"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"Cerbetica10Shadow"
	}
	
	"recordlabel1_Debug"
	{
		"ControlName"	"Label"
		"fieldName"		"recordlabel1_Debug"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f40"
		"tall"			"15"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"RB saved coach"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"Cerbetica10Shadow"
	}
	
	"recordlabel2"
	{
		"ControlName"	"Label"
		"fieldName"		"recordlabel2"
		"xpos"			"0"
		"ypos"			"15"
		"wide"			"f40"
		"tall"			"15"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"RB saved coach"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"Cerbetica10Shadow"
	}
	
	"recordlabel2_Debug"
	{
		"ControlName"	"Label"
		"fieldName"		"recordlabel2_Debug"
		"xpos"			"0"
		"ypos"			"15"
		"wide"			"f40"
		"tall"			"15"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"RB saved coach"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"Cerbetica10Shadow"
	}
	
	"recordlabel3"
	{
		"ControlName"	"Label"
		"fieldName"		"recordlabel3"
		"xpos"			"0"
		"ypos"			"30"
		"wide"			"f40"
		"tall"			"15"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"RB saved coach"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"Cerbetica10Shadow"
	}
	
	"recordlabel3_Debug"
	{
		"ControlName"	"Label"
		"fieldName"		"recordlabel3_Debug"
		"xpos"			"0"
		"ypos"			"30"
		"wide"			"f40"
		"tall"			"15"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"RB saved coach"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"Cerbetica10Shadow"
	}
	
	"recordlabel4"
	{
		"ControlName"	"Label"
		"fieldName"		"recordlabel4"
		"xpos"			"0"
		"ypos"			"45"
		"wide"			"f40"
		"tall"			"15"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"RB saved coach"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"Cerbetica10Shadow"
	}
	
	"recordlabel4_Debug"
	{
		"ControlName"	"Label"
		"fieldName"		"recordlabel4_Debug"
		"xpos"			"0"
		"ypos"			"45"
		"wide"			"f40"
		"tall"			"15"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"RB saved coach"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"Cerbetica10Shadow"
	}
	
	"recordlabel0"
	{
		"ControlName"	"Label"
		"fieldName"		"recordlabel0"
		"xpos"			"0"
		"ypos"			"60"
		"wide"			"f40"
		"tall"			"15"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"RB killed boomer"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"Cerbetica10Shadow"
		//"border"		"baseborder"
		"fgcolor_override" "Ammo In Reserve"
	}
	
	"recordlabel0_Debug"
	{
		"ControlName"	"Label"
		"fieldName"		"recordlabel0_Debug"
		"xpos"			"0"
		"ypos"			"60"
		"wide"			"f40"
		"tall"			"15"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"RB killed boomer"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"Cerbetica10Shadow"
		//"border"		"baseborder"
		"fgcolor_override" "Ammo In Reserve"
	}
}