"Resource/UI/HUD/LocalPlayerPanel_Incap.res"
{
	"BackgroundImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"BackgroundImage"
		"xpos"			"0"
		"ypos"			"25"
		"wide"			"220"
		"tall"			"55"
		"zpos"			"-1"
		"visible"		"0"
		"enabled"		"0"
		"scaleImage"	"1"
		"image"			"hud/healthbar_bg_player"
		"drawColor"	"0 0 0 0"
	}
	"Voice"
	{
		"ControlName"	"TeamDisplayVoicePanel"
		"fieldName"		"Voice"
		"xpos"			"95"
		"ypos"			"215"
		"wide"			"50"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"zpos"			"3"
		"voice_icon"	"voice_self"
	}
	"Head"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"Head"
		"xpos"		"0"
		"ypos"		"r33"
		"wide"		"0"
		"tall"		"0"
		"visible"	"1"
		"enabled"	"1"
		"scaleImage"	"1"
	}
	"Dead"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"Dead"
		"xpos"			"1000"
		"ypos"			"28"
		"wide"			"256"
		"tall"			"128"
		"zpos"			"3"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"
		"image"			"hud/overlay_dead"
	}
	"DuckingIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"DuckingIcon"
		"xpos"			"18"
		"ypos"			"357"
		"wide"			"17"
		"tall"			"17"
		"zpos"		"2"
		"visible"	"1"
		"enabled"	"1"
		"scaleImage"	"1"
		"image"		"hud/crouch_survivor"
	}
	"Health"
	{
		"ControlName"	"HealthPanel"
		"fieldName"		"Health"
		"xpos"			"35"
		"ypos"			"362"
		"wide"			"51"
		"tall"			"13"
		"visible"		"1"
		"enabled"		"1"
		"zpos"			"1"
	}
	"HealthIcon"
	{
		"ControlName"	"Label"
		"fieldName"	"HealthIcon"
		"xpos"		"6"
		"ypos"		"r34"
		"wide"		"70"
		"tall"		"20"
		"visible"	"1"
		"enabled"	"1"
		"labelText"	""
		"textAlignment"	"west"
		"font"		"MainBold"
		"zpos"		"2"
	}
	"HealthNumber"
	{
		"ControlName"	"Label"
		"fieldName"		"HealthNumber"
		"xpos"			"5"
		"ypos"			"325"
		"wide"			"80"
		"tall"			"35"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%HealthNumber%"
		"textAlignment"	"east"
		"font"			"ink_weight_50"
		"zpos"			"0"
	}
}